// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Only the Prisma CLI (migrate, studio, seed) uses this; the app itself
  // connects via lib/db.ts. Migrations need a direct connection, not Neon's
  // pooled one, so prefer the unpooled URL the Vercel/Neon integration sets.
  datasource: {
    url:
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["DIRECT_URL"] ??
      process.env["DATABASE_URL"],
  },
});
